services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - venv:/home/vscode/app/.venv
    shm_size: 32gb
    tty: true
    stdin_open: true

volumes:
  venv:
    driver: local
  hf-cache:
    driver: local
  uv-cache:
    driver: local