"""Training entry point for BoardDetector (raw screenshot -> ShogiBoardView bbox).

Usage:
    python -m mito_train.training.train_detector \\
        --train-manifest data/detector/train.jsonl \\
        --val-manifest data/detector/val.jsonl \\
        --data-root data \\
        --bboxes-json data/test/device_bboxes.json \\
        --epochs 30 --batch-size 32 --lr 3e-4

Split policy: use pre-built jsonl manifests generated by
`scripts/data/build_manifests.py` (stratified per device). This keeps the eval mix
representative of the input devices and reproducible across runs.

Loss: masked Smooth L1 on normalized bbox. Samples where augmentation pushed the
board out of frame (bbox == -1) are skipped from the loss.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from dotenv import load_dotenv

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

from mito_train.datasets import DetectorDataset, build_detector_transform
from mito_train.datasets import HFDetectorDataset
from mito_train.models import BoardDetector
from mito_train.training.train_piece import _init_wandb, get_device


def bbox_iou(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    px1, py1, px2, py2 = pred.unbind(-1)
    tx1, ty1, tx2, ty2 = target.unbind(-1)
    ix1 = torch.max(px1, tx1); iy1 = torch.max(py1, ty1)
    ix2 = torch.min(px2, tx2); iy2 = torch.min(py2, ty2)
    iw = (ix2 - ix1).clamp(min=0); ih = (iy2 - iy1).clamp(min=0)
    inter = iw * ih
    pa = (px2 - px1).clamp(min=0) * (py2 - py1).clamp(min=0)
    ta = (tx2 - tx1).clamp(min=0) * (ty2 - ty1).clamp(min=0)
    union = pa + ta - inter
    return torch.where(union > 0, inter / union, torch.zeros_like(union))


def masked_smooth_l1(pred: torch.Tensor, target: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    mask = (target >= 0).all(dim=-1)  # (B,)
    if mask.sum() == 0:
        return torch.tensor(0.0, device=pred.device, requires_grad=True), mask
    loss = F.smooth_l1_loss(pred[mask], target[mask], beta=0.02)
    return loss, mask


def evaluate(model: nn.Module, loader: DataLoader, device: str) -> dict[str, float]:
    model.eval()
    ious: list[torch.Tensor] = []
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device); y = y.to(device)
            pred = model(x)
            mask = (y >= 0).all(dim=-1)
            if mask.sum() == 0:
                continue
            ious.append(bbox_iou(pred[mask], y[mask]))
    if not ious:
        return {"iou_mean": 0.0, "iou@0.5": 0.0, "iou@0.75": 0.0, "iou@0.9": 0.0}
    iou = torch.cat(ious)
    return {
        "iou_mean": iou.mean().item(),
        "iou@0.5": (iou >= 0.5).float().mean().item(),
        "iou@0.75": (iou >= 0.75).float().mean().item(),
        "iou@0.9": (iou >= 0.9).float().mean().item(),
    }


def main() -> None:
    # Pull HF_TOKEN / WANDB_API_KEY / CF_* out of .env into os.environ before
    # any wandb or HF call resolves credentials. No-op if .env is missing.
    # override=True so devcontainer.json's ${localEnv:...} forwards that expand
    # to an empty string on hosts without those vars don't win over .env.
    load_dotenv(override=True)
    p = argparse.ArgumentParser()
    p.add_argument("--train-manifest", type=Path, default=Path("data/detector/train.jsonl"))
    p.add_argument("--val-manifest", type=Path, default=Path("data/detector/val.jsonl"))
    p.add_argument("--data-root", type=Path, default=Path("data"))
    p.add_argument("--bboxes-json", type=Path, default=Path("data/test/device_bboxes.json"))
    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--image-size", type=int, default=384)
    p.add_argument("--num-workers", type=int, default=4)
    p.add_argument("--out-dir", type=Path, default=Path("runs/board-detector-v1"))
    p.add_argument("--wandb-project", default="mito-train")
    p.add_argument("--wandb-run", default=None)
    p.add_argument("--wandb-run-id", default=None)
    p.add_argument("--wandb-resume", default=None)
    p.add_argument("--resume-from", type=Path, default=None)
    p.add_argument("--hf-repo-id", default=None,
                   help="If set, load train/val from this HF dataset repo instead of local jsonl.")
    p.add_argument("--hf-config", default="detector_paired")
    args = p.parse_args()

    device = get_device()
    print(f"[detector] device={device}")

    train_tf = build_detector_transform("train", args.image_size)
    val_tf = build_detector_transform("val", args.image_size)
    if args.hf_repo_id:
        train_ds = HFDetectorDataset(args.hf_repo_id, "train", train_tf, config_name=args.hf_config, image_size=args.image_size)
        val_ds = HFDetectorDataset(args.hf_repo_id, "val", val_tf, config_name=args.hf_config, image_size=args.image_size)
        print(f"[detector] hf={args.hf_repo_id}/{args.hf_config}")
    else:
        train_ds = DetectorDataset(args.train_manifest, args.data_root, args.bboxes_json, train_tf)
        val_ds = DetectorDataset(args.val_manifest, args.data_root, args.bboxes_json, val_tf)
    print(f"[detector] train={len(train_ds)}, val={len(val_ds)}, devices={sorted(train_ds.bboxes)}")

    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True,
        num_workers=args.num_workers, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.num_workers, pin_memory=True,
    )

    model = BoardDetector(pretrained=True).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    start_epoch = 0
    if args.resume_from and args.resume_from.exists():
        ck = torch.load(args.resume_from, map_location=device, weights_only=False)
        model.load_state_dict(ck["model"])
        opt.load_state_dict(ck["optimizer"])
        start_epoch = ck.get("epoch", 0) + 1
        print(f"[detector] resumed from {args.resume_from} @ epoch {start_epoch}")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    run = _init_wandb(
        args.wandb_project,
        args.wandb_run or "detector",
        vars(args) | {"backbone": "mobilenet_v3_small"},
        run_id=args.wandb_run_id, resume=args.wandb_resume,
    )

    for epoch in range(start_epoch, args.epochs):
        model.train()
        loss_sum = n_seen = 0
        for x, y in train_loader:
            x = x.to(device); y = y.to(device)
            pred = model(x)
            loss, mask = masked_smooth_l1(pred, y)
            if mask.sum() == 0:
                continue
            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()
            loss_sum += loss.item() * mask.sum().item()
            n_seen += mask.sum().item()
        sched.step()
        train_loss = loss_sum / max(1, n_seen)
        metrics = evaluate(model, val_loader, device)
        print(
            f"[detector] epoch {epoch:03d}  "
            f"loss={train_loss:.4f}  "
            f"iou={metrics['iou_mean']:.4f}  "
            f"@0.5={metrics['iou@0.5']:.3f}  "
            f"@0.75={metrics['iou@0.75']:.3f}  "
            f"@0.9={metrics['iou@0.9']:.3f}"
        )
        if run is not None:
            run.log({"train/loss": train_loss, "train/lr": sched.get_last_lr()[0], **{f"val/{k}": v for k, v in metrics.items()}}, step=epoch)

        ck_path = args.out_dir / "latest.pt"
        torch.save(
            {"epoch": epoch, "model": model.state_dict(), "optimizer": opt.state_dict(),
             "backbone": "mobilenet_v3_small", "image_size": args.image_size,
             "devices": sorted(train_ds.bboxes), "wandb_run_id": run.id if run else None},
            ck_path,
        )

    print("[detector] done.")


if __name__ == "__main__":
    main()
